builds:
  - binary: gortcd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - openbsd
      - windows
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 6
      - 7
  - binary: gortcd-pie
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - "-buildmode=pie"

checksum:
  name_template: "{{.ProjectName}}-{{.Version }}-checksums.txt"

dockers:
  - image: gortc/gortcd
    dockerfile: release.Dockerfile
    extra_files:
      - gortcd.yml
    tag_templates:
      - "{{ .Version }}"
      - latest

nfpm:
  formats:
      - deb
  files:
    provision/gortcd.service: /etc/systemd/system/gortcd.service
  scripts:
    postinstall: "provision/postinstall.sh"
  vendor: "gortc.io"
  homepage: "https://gortc.io/"
  maintainer: "Aleksandr Razumov <ar@cydev.ru>"
  description: "TURN and STUN server in go."
  license: "BSD 3-Clause"
  name_template: "{{.ProjectName}}-{{.Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}-{{.Version}}-{{.Os}}-{{.Arch}}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  files:
    - README.md
    - LICENSE
release:
  draft: true
