language: go

sudo: required

services:
  - docker

go:
  - stable
  - master

install:
  - make install

script:
  - make test-e2e
  - make test
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: master
  fast_finish: true
