language: go

sudo: required

services:
  - docker

go:
  - stable

install:
  - go version

script:
  - make test-e2e

after_success:
  - go version

matrix:
  allow_failures:
    - go: master
  fast_finish: true
