language: go

sudo: required

services:
  - docker

go:
  - 1.9.x
  - 1.10.x

install: true

script:
 - ./go.test.sh
 - cd integration-test && ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
