version: '3'

services:
  coturn-client:
    container_name: ci_coturn-client_1
    entrypoint:
      - ./usr/bin/turnutils_uclient
      - "-u"
      - "username"
      - "-w"
      - "secret"
      - "-L"
      - "coturn-client"
      - "-e"
      - "coturn-peer"
      - "turn-server"
    depends_on:
      - turn-server
      - coturn-peer
    links:
      - turn-server
    image: gortc/coturn
  coturn-peer:
    container_name: ci_coturn-peer_1
    entrypoint:
      - ./usr/bin/turnutils_peer
    depends_on:
      - turn-server
    links:
      - turn-server
    image: gortc/coturn
  turn-server:
    container_name: ci_turn-server_1
    build:
      context: ../..
      dockerfile: e2e/coturn-client/server.Dockerfile
      args:
        CI_GO_VERSION: ${CI_GO_VERSION}
    environment:
      - CI_GO_VERSION
